### ISSUE TITLE
Criteria for checking neighbor blocks in `findGeometricMatchesForSingleResults`

### ISSUE THREAD

**Issue by davidhcefx** [beurtschipper/Depix#39]
## Observation

In `findGeometricMatchesForSingleResults` [line 204-206](https://github.com/beurtschipper/Depix/blob/5a124f013c7c1ca37a9b3b67cff3ede2a2c24de5/depixlib/functions.py#L198-L209), there are three `if` conditions:

https://github.com/beurtschipper/Depix/blob/5a124f013c7c1ca37a9b3b67cff3ede2a2c24de5/depixlib/functions.py#L198-L209

To my own understanding, the first `if` is for checking whether the two pixels have the same x and y coordinate differences between the original image and the pixelated one. The second and third `if` once puzzled me, but I think I have figured it out that it was for checking if the two pixels was ***neighbors***.

However, since `width`s and `height`s are always positive, the above condition only matches four cases, for instance:
```
[compareM]        [       ]    ^
                               | singleResult.height
[        ]        [singleM]    v

<--- singleResult.width --->
```
The other three cases were similar, except `singleResult.width ` or `singleResult.height` being replaced by `pixelatedSubRectange.width` or `pixelatedSubRectange.height`.

## Suggestion

My suggestion for a better criteria would be:

```py
if xDistanceMatches == xDistanceRectangles \
		and yDistanceMatches == yDistanceRectangles \
		and xDistanceMatches in [-singleResult.width, 0, pixelatedSubRectange.width] \
		and yDistanceMatches in [-singleResult.height, 0, pixelatedSubRectange.height]:
```

This would match eight cases:
```py
[1]  [2]  [3]

[4]  [S]  [5]   # Assume singleResultMatch being at the center

[6]  [7]  [8]
```

- For compareMatch being at positions 1, 4 and 6, `xDistanceMatches == pixelatedSubRectange.width`
- For positions 2 and 7, `xDistanceMatches == 0`
- For positions 3, 5 and 8, `xDistanceMatches == -singleResult.width`
- `yDistanceMatches` is similar to `xDistanceMatches`

**Comment by beurtschipper** [comment]
Great find! However, have you thought of the corner case where `xDistanceMatches == 0 and yDistanceMatches == 0`?
When I add your code the program (with filtering the corner case) it finds less matches than with the original code. I think this is because it finds more valid matches :+1: 
I'd like to challenge you to implement this code and to write it in such as way that it performs better than the original code.

I've added your addition to the codebase anyway, but if you can make it perform better I suggest you add a pull request.

I addition, I got pointed to this paper today:
https://www.researchgate.net/publication/305423573_On_the_Ineffectiveness_of_Mosaicing_and_Blurring_as_Tools_for_Document_Redaction
It describes a superior strategy for depixelizing text using Hidden Markov Chains. The method greatly outperforms this algorithm, so you can try to implement theirs to make a font-agnostic application.

**Comment by davidhcefx** [comment]
Thanks for accepting my suggestion!
The Markov Chain approach seems promising, but I have already made a pull request anyway.

**Comment by beurtschipper** [comment]
Thanks man! Great job. I've merged the pull request.
