### ISSUE TITLE
Confirmed working software for pixelation?

### ISSUE THREAD

**Issue by LowAmmonia** [beurtschipper/Depix#49]
Hi

Thanks for your work, it is a very interesting project. 
Can you confirm some confirmed working software to perform the pixelation of the text, I have been using Photoshop Elements 15 to pixelate and windows snipping tool to screenshot but without much luck and want to reduce the variables.

I have downloaded greenshot to take screenshots as per a previous comment of yours.

**Comment by toydotgame** [comment]
At this point, it's not a problem on your end - it's a problem with Depix (most likely).
Depix is a relatively poorly-worked-on project, and so it's a matter of time until some big code changes are made in order to make this a really good depixaliser. In it's current state, Depix only works in certain niche scenarios.
For now, we wait. ;)

**Comment by beurtschipper** [comment]
What toydotgame said. This is a PoC not a full-blown all-purpose depixalization application. Go make it yourself if you want it.
